name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  # PROJECT_PATH: 'RepositoryAndUnitOfWork.DataAccess/RepositoryAndUnitOfWork.DataAccess.csproj'
  PROJECT_NAME: 'RepositoryAndUnitOfWork.DataAccess'
  BUILD_CONFIGURATION: 'Release'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: setup NuGet
      uses: Nuget/setup-nuget@v2
      with:
        nuget-version: "latest"

    - name: Debug project location
      shell: powershell
      run: |
       Write-Host "Searching for csproj files..."
       Get-ChildItem -Recurse -Filter "*.csproj" | Select-Object FullName
      

    - name: restore Nuget
      working-directory: RepositoryAndUnitOfWorkPattern/RepositoryAndUnitOfWork.DataAccess
      run: nuget restore RepositoryAndUnitOfWork.DataAccess.csproj

    - name: build project
      run:  |
        msbuild RepositoryAndUnitOfWorkPattern/RepositoryAndUnitOfWork.DataAccess/RepositoryAndUnitOfWork.DataAccess.csproj `
            /p:Configuration=$env:BUILD_CONFIGURATION `
            /p:Platform="Any CPU" `
            /t:Build `
            /v:normal `
            /m

      shell: powershell 

    - name: prepare artifact folder
      run: |
       $buildOutput = Join-Path "${{ env.PROJECT_NAME }}" "bin\${{ env.BUILD_CONFIGURATION }}"
          $artifactDir = "artifacts"

          New-Item -ItemType Directory -Path $artifactDir -Force | Out-Null
          Copy-Item -Path "$buildOutput\*" -Destination $artifactDir -Recurse -Force

          Write-Host "Artifacts prepared from:"
          Write-Host "  $buildOutput"
      shell: powershell 

    - name: package artifact
      run: |
        Compress-Archive -Path artifacts\* -DestinationPath class-library-build.zip -Force

      shell: powershell
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: class-library-build
        path: class-library-build.zip