name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  # PROJECT_PATH: 'RepositoryAndUnitOfWork.DataAccess/RepositoryAndUnitOfWork.DataAccess.csproj'
  SOLUTION_PATH: 'RepositoryAndUnitOfWorkPattern/RepositoryAndUnitOfWork.sln'
  BUILD_CONFIGURATION: 'Release'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: setup NuGet
      uses: Nuget/setup-nuget@v2
      with:
        nuget-version: "latest"
    - name: restore Nuget
      run: nuget restore ${{ env.SOLUTION_PATH }}

    - name: build solution
      run:  |
        msbuild ${{ env.SOLUTION_PATH }} `
            /p:Configuration=$env:BUILD_CONFIGURATION `
            /p:Platform="Any CPU" `
            /t:Build `
            /v:normal `
            /m

      shell: powershell 

    - name: collect built artifact
      run: |
        New-Item -ItemType Directory -Path artifacts -Force | Out-Null

          Copy-Item `
            -Path "RepositoryAndUnitOfWorkPattern/**/bin/${{ env.BUILD_CONFIGURATION }}/*" `
            -Destination artifacts `
            -Recurse -Force
      shell: powershell

    - name: package artifact
      run: |
        Compress-Archive -Path artifacts\* -DestinationPath dotnet-framework-build.zip -Force
      shell: powershell
      
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-framework-build
        path: dotnet-framework-build.zip